<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class DeviceSeeder extends Seeder
{
    public static function run()
    {
        $now = Carbon::now('utc')->toDateTimeString();

        \App\Models\Device::insert([
            [
                'client_id' => random_int(1, 6),
                'device_type_id' => random_int(1, 6),
                'code' => 'AA158',
                'name' => 'Bomba autoescorvante',
                'alert_level_1' => 10,
                'alert_level_2' => 20,
                'total_liter' => 10000,
                'ordem' => 1,
                'classification_1' => 'Classif 1',
                'classification_2' => 'Classif 2',
                'classification_3' => 'Classif 3',
                'maintenance_last_1' => $now,
                'maintenance_last_2' => '',
                'maintenance_next_1' => 3000,
                'maintenance_next_2' => 10000,
                'status' => (bool)random_int(0, 1),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'client_id' => random_int(1, 6),
                'device_type_id' => random_int(1, 6),
                'code' => 'AA158',
                'name' => 'Bomba Submersível',
                'alert_level_1' => 10,
                'alert_level_2' => 20,
                'total_liter' => 10000,
                'ordem' => 1,
                'classification_1' => 'Classif 1',
                'classification_2' => 'Classif 2',
                'classification_3' => 'Classif 3',
                'maintenance_last_1' => $now,
                'maintenance_last_2' => '',
                'maintenance_next_1' => 3000,
                'maintenance_next_2' => 10000,
                'status' => (bool)random_int(0, 1),
                'created_at' => $now,
                'updated_at' => $now,
            ],[
                'client_id' => random_int(1, 6),
                'device_type_id' => random_int(1, 6),
                'code' => 'AA158',
                'name' => 'Bomba Multiestágio',
                'alert_level_1' => 10,
                'alert_level_2' => 20,
                'total_liter' => 10000,
                'ordem' => 1,
                'classification_1' => 'Classif 1',
                'classification_2' => 'Classif 2',
                'classification_3' => 'Classif 3',
                'maintenance_last_1' => $now,
                'maintenance_last_2' => '',
                'maintenance_next_1' => 3000,
                'maintenance_next_2' => 10000,
                'status' => (bool)random_int(0, 1),
                'created_at' => $now,
                'updated_at' => $now,
            ],[
                'client_id' => random_int(1, 6),
                'device_type_id' => random_int(1, 6),
                'code' => 'AA158',
                'name' => 'Bomba Monoestágio',
                'alert_level_1' => 10,
                'alert_level_2' => 20,
                'total_liter' => 10000,
                'ordem' => 1,
                'classification_1' => 'Classif 1',
                'classification_2' => 'Classif 2',
                'classification_3' => 'Classif 3',
                'maintenance_last_1' => $now,
                'maintenance_last_2' => '',
                'maintenance_next_1' => 3000,
                'maintenance_next_2' => 10000,
                'status' => (bool)random_int(0, 1),
                'created_at' => $now,
                'updated_at' => $now,
            ],[
                'client_id' => random_int(1, 6),
                'device_type_id' => random_int(1, 6),
                'code' => 'AA158',
                'name' => 'Bomba Submersa',
                'alert_level_1' => 10,
                'alert_level_2' => 20,
                'total_liter' => 10000,
                'ordem' => 1,
                'classification_1' => 'Classif 1',
                'classification_2' => 'Classif 2',
                'classification_3' => 'Classif 3',
                'maintenance_last_1' => $now,
                'maintenance_last_2' => '',
                'maintenance_next_1' => 3000,
                'maintenance_next_2' => 10000,
                'status' => (bool)random_int(0, 1),
                'created_at' => $now,
                'updated_at' => $now,
            ],[
                'client_id' => random_int(1, 6),
                'device_type_id' => random_int(1, 6),
                'code' => 'AA158',
                'name' => 'Bomba Mancal',
                'alert_level_1' => 10,
                'alert_level_2' => 20,
                'total_liter' => 10000,
                'ordem' => 1,
                'classification_1' => 'Classif 1',
                'classification_2' => 'Classif 2',
                'classification_3' => 'Classif 3',
                'maintenance_last_1' => $now,
                'maintenance_last_2' => '',
                'maintenance_next_1' => 3000,
                'maintenance_next_2' => 10000,
                'status' => (bool)random_int(0, 1),
                'created_at' => $now,
                'updated_at' => $now,
            ]
        ]);
    }
}